### ISSUE TITLE
[Version 0.6.0] - First time install crashes on Apple M1

### ISSUE THREAD

**Issue by peter-dough** [doitintl/kube-no-trouble#392]
Hello DoIT Team,

I just installed `kube-no-trouble` for the first time and received the error below. I am also using a macbook with an M1 processor. Could this be related to the error? Please advise.

```
❯ kubent
1:54PM INF >>> Kube No Trouble `kubent` <<<
1:54PM INF version 0.6.0 (git sha 126e47b9b45550a45404b599c546bf911ffae571)
1:54PM INF Initializing collectors and retrieving data
unexpected fault address 0x36080808e47f7649
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x36080808e47f7649 pc=0x10230ab60]

goroutine 1 [running]:
runtime.throw({0x10303ed27?, 0x30?})
	/usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x14000119690 sp=0x14000119660 pc=0x1022dd860
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:842 +0x1a0 fp=0x140001196c0 sp=0x14000119690 pc=0x1022f3ba0
aeshashbody()
	/usr/local/go/src/runtime/asm_arm64.s:791 +0x2d0 fp=0x140001196d0 sp=0x140001196d0 pc=0x10230ab60
runtime.mapiternext(0x140004a5e80)
	/usr/local/go/src/runtime/map.go:936 +0x2d8 fp=0x14000119740 sp=0x140001196d0 pc=0x1022b6a38
runtime.mapiterinit(0x1033dc950?, 0x7?, 0x140001197c8?)
	/usr/local/go/src/runtime/map.go:863 +0x2e8 fp=0x14000119770 sp=0x14000119740 pc=0x1022b6718
reflect.mapiterinit(0x10ba0bfff?, 0x1400042f770?, 0x140001197f8?)
	/usr/local/go/src/runtime/map.go:1375 +0x1c fp=0x140001197a0 sp=0x14000119770 pc=0x10230717c
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0x1400028b470, 0x1400000ddb0, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:291 +0x23c fp=0x14000119920 sp=0x140001197a0 pc=0x1027f3b3c
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x10be00e01?, 0x1400069d638?, 0x140001199c8?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x28 fp=0x14000119950 sp=0x14000119920 pc=0x1027ecae8
github.com/json-iterator/go.(*structFieldEncoder).Encode(0x1400028b6e0, 0x103297937?, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x54 fp=0x140001199d0 sp=0x14000119950 pc=0x1027fffc4
github.com/json-iterator/go.(*structEncoder).Encode(0x1400028b740, 0x68b?, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x708 fp=0x14000119ac0 sp=0x140001199d0 pc=0x102800948
github.com/json-iterator/go.(*OptionalEncoder).Encode(0x1400069d620?, 0x140001ad7d0?, 0x14000119b68?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xc8 fp=0x14000119b20 sp=0x14000119ac0 pc=0x1027f8d08
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x14000119b01?, 0x1400069d638?, 0x14000119bc8?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x28 fp=0x14000119b50 sp=0x14000119b20 pc=0x1027ecae8
github.com/json-iterator/go.(*structFieldEncoder).Encode(0x14000304bd0, 0x1032c7e3b?, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x54 fp=0x14000119bd0 sp=0x14000119b50 pc=0x1027fffc4
github.com/json-iterator/go.(*structEncoder).Encode(0x14000304c90, 0x140001d3ec0?, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x708 fp=0x14000119cc0 sp=0x14000119bd0 pc=0x102800948
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x14000224601?, 0x1400069d638?, 0x14000119d68?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x28 fp=0x14000119cf0 sp=0x14000119cc0 pc=0x1027ecae8
github.com/json-iterator/go.(*structFieldEncoder).Encode(0x14000304f00, 0x1032978f7?, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x54 fp=0x14000119d70 sp=0x14000119cf0 pc=0x1027fffc4
github.com/json-iterator/go.(*structEncoder).Encode(0x14000304f60, 0x1022b1008?, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x708 fp=0x14000119e60 sp=0x14000119d70 pc=0x102800948
github.com/json-iterator/go.(*sliceEncoder).Encode(0x14000436ed0, 0x140001ed4f8, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_slice.go:42 +0x334 fp=0x14000119f20 sp=0x14000119e60 pc=0x1027f97b4
github.com/json-iterator/go.(*structFieldEncoder).Encode(0x14000305aa0, 0x10329d36e?, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x54 fp=0x14000119fa0 sp=0x14000119f20 pc=0x1027fffc4
github.com/json-iterator/go.(*structEncoder).Encode(0x14000305bc0, 0x1400019efd0?, 0x1400069d620)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x708 fp=0x1400011a090 sp=0x14000119fa0 pc=0x102800948
github.com/json-iterator/go.(*OptionalEncoder).Encode(0x1033f7c20?, 0x14000222aa0?, 0x0?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xc8 fp=0x1400011a0f0 sp=0x1400011a090 pc=0x1027f8d08
github.com/json-iterator/go.(*onePtrEncoder).Encode(0x14000140ba0, 0x140001ed4a0, 0x14000193020?)
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x88 fp=0x1400011a130 sp=0x1400011a0f0 pc=0x1027ec108
github.com/json-iterator/go.(*Stream).WriteVal(0x1400069d620, {0x1033f7c20, 0x140001ed4a0})
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x170 fp=0x1400011a1b0 sp=0x1400011a130 pc=0x1027eb4f0
github.com/json-iterator/go.(*frozenConfig).Marshal(0x14000222aa0, {0x1033f7c20, 0x140001ed4a0})
	/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299 +0x88 fp=0x1400011a250 sp=0x1400011a1b0 pc=0x1027e29e8
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x10327d676?, {0x103524088?, 0x140001ed4a0?}, {0x10351c380, 0x1400023b710})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/serializer/json/json.go:305 +0x54 fp=0x1400011a2f0 sp=0x1400011a250 pc=0x102811614
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0x140003b00f0, {0x103524088, 0x140001ed4a0}, {0x10351c380, 0x1400023b710})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/serializer/json/json.go:300 +0xe0 fp=0x1400011a350 sp=0x1400011a2f0 pc=0x102811580
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0x14000446820, {0x103524038?, 0x1400069d560}, {0x10351c380, 0x1400023b710})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/serializer/versioning/versioning.go:244 +0x680 fp=0x1400011a6e0 sp=0x1400011a350 pc=0x10281dc60
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0x14000446820, {0x103524038, 0x1400069d560}, {0x10351c380, 0x1400023b710})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/serializer/versioning/versioning.go:184 +0xe0 fp=0x1400011a740 sp=0x1400011a6e0 pc=0x10281d5a0
k8s.io/apimachinery/pkg/runtime.Encode({0x10be98d18, 0x14000446820}, {0x103524038, 0x1400069d560})
	/go/pkg/mod/k8s.io/apimachinery@v0.17.13/pkg/runtime/codec.go:50 +0x60 fp=0x1400011a780 sp=0x1400011a740 pc=0x1025dce20
k8s.io/client-go/tools/clientcmd.Write(...)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/tools/clientcmd/loader.go:469
k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x14000238300}, 0x14000238330, 0x14000238360, 0x14000238390, {0x140001d3e90, ...}, ...}, ...)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/tools/clientcmd/loader.go:422 +0xe0 fp=0x1400011a800 sp=0x1400011a780 pc=0x102fed510
k8s.io/client-go/tools/clientcmd.ModifyConfig({0x1035321e0, 0x140003b08c0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x14000128960}, 0x14000128990, 0x140001289c0, ...}, ...)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/tools/clientcmd/config.go:280 +0x9d0 fp=0x1400011af30 sp=0x1400011a800 pc=0x102fea1a0
k8s.io/client-go/tools/clientcmd.(*persister).Persist(0x140001c9da0, 0x14000406240)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/tools/clientcmd/config.go:363 +0xf4 fp=0x1400011b020 sp=0x1400011af30 pc=0x102fea904
k8s.io/client-go/plugin/pkg/client/auth/gcp.(*cachedTokenSource).Token(0x14000100f60)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/plugin/pkg/client/auth/gcp/gcp.go:225 +0xd8 fp=0x1400011b090 sp=0x1400011b020 pc=0x103037da8
golang.org/x/oauth2.(*Transport).RoundTrip(0x1400028cd00, 0x14000356f00)
	/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210514164344-f6687ab2804c/transport.go:45 +0x98 fp=0x1400011b1b0 sp=0x1400011b090 pc=0x102cd9b38
k8s.io/client-go/plugin/pkg/client/auth/gcp.(*conditionalTransport).RoundTrip(0x1400028cce0, 0x14000356f00)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/plugin/pkg/client/auth/gcp/gcp.go:369 +0x4c fp=0x1400011b200 sp=0x1400011b1b0 pc=0x103038f4c
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0x1400028cd20, 0x14000356d00)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/transport/round_trippers.go:159 +0x2d0 fp=0x1400011b300 sp=0x1400011b200 pc=0x102cdbac0
net/http.send(0x14000356c00, {0x10351e120, 0x1400028cd20}, {0x10259534c?, 0x8?, 0x103f34be0?})
	/usr/local/go/src/net/http/client.go:251 +0x4f4 fp=0x1400011b500 sp=0x1400011b300 pc=0x102593ba4
net/http.(*Client).send(0x1400028a720, 0x14000356c00, {0x1400011b5e8?, 0x10230a67c?, 0x103f34be0?})
	/usr/local/go/src/net/http/client.go:175 +0x98 fp=0x1400011b580 sp=0x1400011b500 pc=0x102593548
net/http.(*Client).do(0x1400028a720, 0x14000356c00)
	/usr/local/go/src/net/http/client.go:715 +0x6e8 fp=0x1400011b780 sp=0x1400011b580 pc=0x1025953a8
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:581
k8s.io/client-go/rest.(*Request).request(0x14000480690, 0x1400011b968?)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/rest/request.go:801 +0x3bc fp=0x1400011b910 sp=0x1400011b780 pc=0x102cf645c
k8s.io/client-go/rest.(*Request).Do(0x14000480690)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/rest/request.go:873 +0x7c fp=0x1400011b9f0 sp=0x1400011b910 pc=0x102cf6ddc
k8s.io/client-go/discovery.(*DiscoveryClient).ServerVersion(0x1400011bb68?)
	/go/pkg/mod/k8s.io/client-go@v0.17.13/discovery/discovery_client.go:408 +0x5c fp=0x1400011bb10 sp=0x1400011b9f0 pc=0x102cfd00c
github.com/doitintl/kube-no-trouble/pkg/collector.(*kubeCollector).GetServerVersion(0x0?)
	/__w/kube-no-trouble/kube-no-trouble/pkg/collector/kube.go:71 +0x2c fp=0x1400011bbf0 sp=0x1400011bb10 pc=0x102ff3c3c
main.getServerVersion(0x0, {0x140001a3540?, 0x3, 0x1400011bdc0?})
	/__w/kube-no-trouble/kube-no-trouble/cmd/kubent/main.go:88 +0x9c fp=0x1400011bc50 sp=0x1400011bbf0 pc=0x10303bb6c
main.main()
	/__w/kube-no-trouble/kube-no-trouble/cmd/kubent/main.go:123 +0x3e0 fp=0x1400011bf70 sp=0x1400011bc50 pc=0x10303bfe0
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x24c fp=0x1400011bfd0 sp=0x1400011bf70 pc=0x1022dfddc
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400011bfd0 sp=0x1400011bfd0 pc=0x10230d9a4

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000070fa0 sp=0x14000070f80 pc=0x1022e01a4
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xac fp=0x14000070fd0 sp=0x14000070fa0 pc=0x1022e003c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000070fd0 sp=0x14000070fd0 pc=0x10230d9a4
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000071770 sp=0x14000071750 pc=0x1022e01a4
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:297 +0x10c fp=0x140000717b0 sp=0x14000071770 pc=0x1022cb92c
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x140000717d0 sp=0x140000717b0 pc=0x1022bfe88
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000717d0 sp=0x140000717d0 pc=0x10230d9a4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x74

goroutine 4 [sleep]:
runtime.gopark(0x1400018c000?, 0xf1c13d573498?, 0x0?, 0x0?, 0x103519698?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000071f00 sp=0x14000071ee0 pc=0x1022e01a4
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).sleep(0x103f34d60, 0x40b6750000000000)
	/usr/local/go/src/runtime/mgcscavenge.go:468 +0x134 fp=0x14000071f80 sp=0x14000071f00 pc=0x1022c9a84
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:626 +0x9c fp=0x14000071fb0 sp=0x14000071f80 pc=0x1022c9e7c
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x14000071fd0 sp=0x14000071fb0 pc=0x1022bfe28
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000071fd0 sp=0x14000071fd0 pc=0x10230d9a4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xb8

goroutine 17 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400006c580 sp=0x1400006c560 pc=0x1022e01a4
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x120 fp=0x1400006c7d0 sp=0x1400006c580 pc=0x1022bf0b0
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400006c7d0 sp=0x1400006c7d0 pc=0x10230d9a4
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x84

goroutine 18 [chan receive]:
runtime.gopark(0x1400006cef8?, 0x10230a67c?, 0x0?, 0x0?, 0x1400004e058?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400006cea0 sp=0x1400006ce80 pc=0x1022e01a4
runtime.chanrecv(0x14000100060, 0x1400006cf90, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x454 fp=0x1400006cf30 sp=0x1400006cea0 pc=0x1022adb04
runtime.chanrecv2(0x12a05f200?, 0x0?)
	/usr/local/go/src/runtime/chan.go:447 +0x14 fp=0x1400006cf60 sp=0x1400006cf30 pc=0x1022ad694
k8s.io/klog.(*loggingT).flushDaemon(0x0?)
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x5c fp=0x1400006cfb0 sp=0x1400006cf60 pc=0x1024c658c
k8s.io/klog.init.0.func1()
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0x28 fp=0x1400006cfd0 sp=0x1400006cfb0 pc=0x1024c4528
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400006cfd0 sp=0x1400006cfd0 pc=0x10230d9a4
created by k8s.io/klog.init.0
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0x144

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400006d740 sp=0x1400006d720 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x1400006d7d0 sp=0x1400006d740 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400006d7d0 sp=0x1400006d7d0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 33 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x140000a2740 sp=0x140000a2720 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000a27d0 sp=0x140000a2740 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000a27d0 sp=0x140000a27d0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x0?, 0x2?, 0x40?, 0x16?, 0x1400007c000?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000070740 sp=0x14000070720 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000707d0 sp=0x14000070740 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000707d0 sp=0x140000707d0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400006df40 sp=0x1400006df20 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x1400006dfd0 sp=0x1400006df40 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400006dfd0 sp=0x1400006dfd0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x103f70d00?, 0x1?, 0x9f?, 0x4d?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000072740 sp=0x14000072720 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000727d0 sp=0x14000072740 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000727d0 sp=0x140000727d0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 21 [GC worker (idle)]:
runtime.gopark(0xf1c0acab097b?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400006e740 sp=0x1400006e720 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x1400006e7d0 sp=0x1400006e740 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400006e7d0 sp=0x1400006e7d0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 7 [GC worker (idle)]:
runtime.gopark(0xf1c0acabef23?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000072f40 sp=0x14000072f20 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000072fd0 sp=0x14000072f40 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000072fd0 sp=0x14000072fd0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x103f70d00?, 0x1?, 0xf1?, 0xbe?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000073740 sp=0x14000073720 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000737d0 sp=0x14000073740 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000737d0 sp=0x140000737d0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 9 [GC worker (idle)]:
runtime.gopark(0xf1c0acabecdb?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000073f40 sp=0x14000073f20 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000073fd0 sp=0x14000073f40 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000073fd0 sp=0x14000073fd0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 22 [GC worker (idle)]:
runtime.gopark(0xf1c0acac8875?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400006ef40 sp=0x1400006ef20 pc=0x1022e01a4
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x1400006efd0 sp=0x1400006ef40 pc=0x1022c226c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400006efd0 sp=0x1400006efd0 pc=0x10230d9a4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 10 [select]:
runtime.gopark(0x140000a3798?, 0x3?, 0x0?, 0x0?, 0x140000a377a?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000698e10 sp=0x14000698df0 pc=0x1022e01a4
runtime.selectgo(0x14000698f98, 0x140000a3774, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:328 +0x688 fp=0x14000698f30 sp=0x14000698e10 pc=0x1022f0038
net/http.setRequestCancel.func4()
	/usr/local/go/src/net/http/client.go:397 +0x74 fp=0x14000698fd0 sp=0x14000698f30 pc=0x102594884
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000698fd0 sp=0x14000698fd0 pc=0x10230d9a4
created by net/http.setRequestCancel
	/usr/local/go/src/net/http/client.go:396 +0x3b0
```

**Comment by stepanstipl** [comment]
Thanks @peter-dough. This seems to be similar/same issue as #390. I'm still trying to narrow this down.

Can you please try one thing - run `kubectl` first, and then `kubent`, and see if it helps? Thanks 👍

**Comment by peter-dough** [comment]
> Thanks @peter-dough. This seems to be similar/same issue as #390. I'm still trying to narrow this down.
> 
> Can you please try one thing - run `kubectl` first, and then `kubent`, and see if it helps? Thanks 👍

interesting, i ran `kubectl get pods` then ran `kubent` and it ran successfully.

**Comment by stepanstipl** [comment]
Ok, thanks for confirming, this is the same issue as #390 then, so I'm going to close this as a duplicate, please follow #390 for updates. To explain the behaviour - it's related to authentication issue - if the auth token needs to be refreshed, this error happens. If you run `kubectl` first, it will refresh the token which stays valid for some time (typically 1h, but that depends on provider/cluster specifics), and therefore `kubent`doesn't have to refresh it and will work for a while, until the token expires. More in #390. So the work-around, until we fix this, is to run `kubectl` first 🙈 .

**Comment by stepanstipl** [comment]
There is now [0.7.0](https://github.com/doitintl/kube-no-trouble/releases/tag/0.7.0) release where this should be fixed. Thanks for your help with this! 🎉
